using System.Collections;

static class Knowlage {
    public static short[] basic_ports = {
        21, 22, 23, 25, 38, 53, 67, 80, 110, 135, 139, 170, 239, 389, 443, 445, 515, 631, 636, 853, 990, 992, 993, 995, 3389, 5900, 6789, 7442, 7550, 8080, 8443, 9100, 10001
    };

    public static Hashtable protocol = new Hashtable() {
        {1,    "TCPMUX, TCP Port Service Multiplexer"},
        {5,    "RJE, Remote Job Entry"},
        {7,    "Echo"},
        {13,   "Daytime Protocol"},
        {17,   "QOTD, Quote of the Day"},
        {18,   "MSP, Message Send Protocol"},
        {19,   "CHARGEN, Character Generator Protocol"},
        {20,   "FTP, File Transfer Protocol - data"},
        {21,   "FTP, File Transfer Protocol - control"},
        {22,   "SSH, Secure Shell"},
        {23,   "Telnet"},
        {25,   "SMTP, Simple Message Transfer Protocol"},
        {26,   "RSFTP"},
        {37,   "Time Protocol"},
        {38,   "RAP, Route Access Protocol"},
        {39,   "RLP, Resource Location Protocol"},
        {42,   "WINS, Windows Internet Name Service"},
        {43,   "WHOIS, Who Is Protocol"},
        {49,   "TACACS, Terminal Access Controller Access-Control System"},
        {53,   "DNS, Domain Name Server"},
        {57,   "MTP, Mail Transfet Protocol"},
        {67,   "DHCP, Dynamic Host Configuration Protocol"},
        {70,   "Gopher, Gopher Protocol"},
        {71,   "NETRJS, Remote Job Entry"},
        {72,   "NETRJS, Remote Job Entry"},
        {73,   "NETRJS, Remote Job Entry"},
        {74,   "NETRJS, Remote Job Entry"},
        {79,   "Finger"},
        {80,   "HTTP, Hypertext Transfer Protocol"},
        {81,   "TOR, The Onion Router"},
        {88,   "Kerberos, Kerberos authentication system"},
        {92,   "NPP, Network Printing Protocol"},
        {109,  "POP2, Post Office Protocol"},
        {110,  "POP3, Post Office Protocol"},
        {111,  "ONC, RPC Open Network Computing Remote Procedure Call"},
        {118,  "SQL, Structured Query Language Services"},
        {119,  "NNTP, Network News Transfer Protocol"},
        {123,  "NTP, Network Time Protocol"},
        {135,  "RPC, Remote Procedure Call"},
        {137,  "NetBIOS, Name Service"},
        {139,  "NetBIOS, Session Service"},
        {143,  "IMAP, Internet Message Access Protocol"},
        {153,  "SGMP, Simple Gateway Monitoring Protocol"},
        {156,  "SQL, Structured Query Language Service"},
        {158,  "DMSP, Distributed Mail Service Protocol"},
        {170,  "Print server"},
        {194,  "IRC, Internet Relay Chat"},
        {213,  "IPX, Internetwork Packet Exchange"},
        {218,  "MPP, Message posting protocol"},
        {220,  "IMAP, Internet Message Access Protocol"},
        {259,  "ESRO, Efficient Short Remote Operations"},
        {264,  "BGMP, Border Gateway Multicast Protocol"},
        {318,  "TSP, Time Stamp Protocol"},
        {387,  "AURP, AppleTalk Update-based Routing Protocol"},
        {389,  "LDAP, Lightweight Directory Access Protocol"},
        {401,  "UPS, Uninterruptible Power Supply"},
        {427,  "SLP, Service Location Protocol"},
        {443,  "HTTP over SSL/TSL"},
        {444,  "SNPP, Simple Network Paging Protocol"},
        {445,  "SMB, Server Message Block"},
        {515,  "LPD, Line Printer Daemon"},
        {524,  "NCP"},
        {540,  "UUCP, Unix-to-Unix Copy Protocol"},
        {547,  "DHCPv6"},
        {548,  "AFP, Apple Filing Protocol"},
        {554,  "RTSP, Real Time Streaming Protocol"},
        {563,  "NNTP protocol over TLS/SSL"},
        {587,  "MSA, Message Aubmission Agent"},
        {625,  "ODProxy, Open Directory Proxy"},
        {631,  "IPP, Internet Printing Protocol"},
        {636,  "LDAP over SSL/TSL"},
        {639,  "MSDP, Multicast Source Discovery Protocol"},
        {646,  "LDP, Label Distribution Protocol"},
        {647,  "DHCP Failover Protocol"},
        {648,  "RRP, Registry Registrar Protocol"},
        {652,  "DTCP, Dynamic Tunnel Configuration Protocol"},
        {674,  "ACAP, Application Configuration Access Protocol"},
        {691,  "MS Exchange Routing"},
        {695,  "IEEE-MMS-SSL"},
        {698,  "OLSR, Optimized Link State Routing"},
        {699,  "Access Network"},
        {700,  "EPP, Extensible Provisioning Protocol"},
        {701,  "LMP, Link Management Protocol"},
        {702,  "IRIS over BEEP" },
        {706,  "SILC, Secure Internet Live Conferencing"},
        {711,  "TDP, Tag Distribution Protocol"},
        {712,  "TBRPF, Topology Broadcast based on Reverse-Path Forwarding"},
        {720,  "SMQP, Simple Message Queue Protocol"},
        {829,  "CMP, Certificate Management Protocol"},
        {853,  "DNS over SSL/TSL"},
        {901,  "SWAT, Samba Web Administration Tool"},
        {902,  "VMware Server"},
        {989,  "FTPS over SSL/TSL, File Transfer Protocol - data"},
        {990,  "FTPS over SSL/TSL, File Transfer Protocol - control"},
        {991,  "NAS, Netnews Admin System"},
        {992,  "Telnet over SSL/TSL"},
        {993,  "IMAP over SSL/TSL"},
        {995,  "POP3 over SSL/TSL"},
        {1433, "MS-SQL, Microsoft SQL server"},
        {3389, "RDP, Remote Desktop Protocol"},
        {5500, "VNC, Virtual Network Computer"},
        {5656, "UniFi AP-EDU broadcasting"},
        {5657, "UniFi AP-EDU broadcasting"},
        {5658, "UniFi AP-EDU broadcasting"},
        {5659, "UniFi AP-EDU broadcasting"},
        {5800, "VNC, Virtual Network Computer"},
        {5801, "VNC, Virtual Network Computer"},
        {5900, "uVNC, Virtual Network Computer"},
        {5901, "uVNC, Virtual Network Computer"},
        {5902, "uVNC, Virtual Network Computer"},
        {5903, "uVNC, Virtual Network Computer"},
        {6666, "UniFi Camera Stream Listenner"},
        {6789, "UniFi Mobile Speed Test"},
        {7004, "UniFi UVC-Micro Talkback"},
        {7442, "UniFi Camera Management"},
        {7447, "UniFi RTSP, Real Time Streaming Protocol"},
        {7680, "WUDO, Windows Update Delivery Optimization"},
        {8080, "HTTP alternate, Hypertext Transfer Protocol"},
        {8291, "Mikrotik RouterOS Winbox"},
        {8443, "HTTP over SSL/TSL alternate"},
        {8728, "Mikrotik RouterOS API"},
        {8729, "Mikrotik RouterOS API over SSL/TSL"},
        {9100, "Print Server"},
        {10000,"NDMP, Network Data Management Protocol"},
        {10001,"UniFi Discovery Service"}
    };

}