name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and test

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ "9.0.x", "10.0.x" ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore
      run: dotnet restore OpenProtest.slnx

    - name: Build
      run: dotnet build OpenProtest.slnx --configuration Release --no-restore

    - name: Test
      run: dotnet test OpenProtest.slnx --configuration Release --no-build