name: Snyk Security

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code test
        run: snyk code test --sarif-file-output=snyk-code.sarif
        continue-on-error: true

      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects
        continue-on-error: true

      - name: Snyk IaC test and report
        run: snyk iac test --report
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t your/image-to-test .

      - name: Snyk Container monitor
        run: snyk container monitor your/image-to-test --file=Dockerfile
        continue-on-error: true

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif